### PR TITLE
Menu and Pause Menu enhancements

### LINKED ISSUE #209: New pause menu format
The format does not work on very large or very small screens because it uses fixed pixels for sizing

### PR DESCRIPTION
**Pull request by codecreativity**
Fixes #209

### CODE REVIEW

File: unity/Assets/0Refactored/reusableGui/Menu/PrefabsColumns/scrMenuColumnLanguage.cs [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+    }
+
+    private void OnClickEnglish()
+    {
+        LanguageManager.Instance.CurrentLanguage = SystemLanguage.English;
+        this.UpdateLocalizedText();
+        this.UpdateActiveButton();
+    }
+
+    private void UpdateLocalizedText()
```
Comment (michaelholly) [inline unity/Assets/0Refactored/reusableGui/Menu/PrefabsColumns/scrMenuColumnLanguage.cs:38]: We do not need this function.
There is an OnLanguageChange event where the LocalizedText is attached and updates itself when the language is changed.
